### PR TITLE
Bump up version to 2.14.0.

### PR DESCRIPTION
**Pull request by csadorf**

### CODE REVIEW

**Comment by scopatz** [comment]
Seems like there is a failure on linux.

**Comment by csadorf** [comment]
I'm going to wait and see if there is a similar issue on the other systems before I start debugging.

**Comment by scopatz** [comment]
Ok @csadorf, I personally would recommend against that since the mac builds on Travis can take a few days.

**Comment by csadorf** [comment]
Ok, I'll see what I can do.

**Comment by csadorf** [comment]
@scopatz Looks like the PR is good to go!

**Comment by scopatz** [comment]
Thanks @csadorf!

**Pull request merged**
